#!/usr/bin/env python3
"""Add just-the-docs nav front matter to tfplugindocs' generated docs/*.md.

tfplugindocs only emits `page_title`/`subcategory`/`description` -- the
just-the-docs Jekyll theme (used for this repo's GitHub Pages site) reads
its own `title`/`parent`/`nav_order`/`has_children` keys instead. Rather
than fighting tfplugindocs' template system, this runs as a fixed
post-processing pass right after `tfplugindocs generate` (see
scripts/gen-docs.sh) and is idempotent -- safe to re-run after every
regeneration.

docs/index.md, docs/resources.md, and docs/data-sources.md are hand-
written (not touched here). Only the generated per-resource /
per-data-source pages under docs/resources/ and docs/data-sources/ are
rewritten.
"""

import pathlib
import sys

import yaml

DOCS_DIR = pathlib.Path(__file__).resolve().parent.parent / "docs"

GENERATED_COMMENT = "# generated by https://github.com/hashicorp/terraform-plugin-docs"


def split_front_matter(text: str) -> tuple[str, str]:
    """Return (front_matter_yaml, body) for a `---\\n...\\n---\\nbody` file."""
    if not text.startswith("---\n"):
        raise ValueError("file does not start with a front matter block")
    end = text.index("\n---\n", 4)
    fm = text[4:end]
    body = text[end + len("\n---\n") :]
    return fm, body


def process_dir(dirname: str, parent_title: str) -> None:
    d = DOCS_DIR / dirname
    if not d.is_dir():
        return
    for path in sorted(d.glob("*.md")):
        text = path.read_text()
        fm_text, body = split_front_matter(text)
        # Strip the leading YAML comment before parsing -- PyYAML round
        # trips comments fine on load (they're just ignored), but re-adding
        # it verbatim on dump keeps a stable diff instead of relying on
        # PyYAML to re-emit a comment it never actually stored.
        fm_lines = [
            line for line in fm_text.split("\n") if line.strip() != GENERATED_COMMENT
        ]
        data = yaml.safe_load("\n".join(fm_lines)) or {}

        resource_name = "sylve_" + path.stem
        data["title"] = resource_name
        data["parent"] = parent_title

        new_fm = yaml.safe_dump(data, default_flow_style=False, sort_keys=False)
        path.write_text(f"---\n{GENERATED_COMMENT}\n{new_fm}---\n{body}")
        print(f"  {path.relative_to(DOCS_DIR.parent)}: title={resource_name!r} parent={parent_title!r}")


def process_index() -> None:
    path = DOCS_DIR / "index.md"
    text = path.read_text()
    fm_text, body = split_front_matter(text)
    fm_lines = [line for line in fm_text.split("\n") if line.strip() != GENERATED_COMMENT]
    data = yaml.safe_load("\n".join(fm_lines)) or {}

    data["title"] = "Home"
    data["nav_order"] = 1

    new_fm = yaml.safe_dump(data, default_flow_style=False, sort_keys=False)
    path.write_text(f"---\n{GENERATED_COMMENT}\n{new_fm}---\n{body}")
    print(f"  docs/index.md: title='Home' nav_order=1")


def main() -> None:
    print("Adding just-the-docs nav front matter...")
    process_index()
    process_dir("resources", "Resources")
    process_dir("data-sources", "Data Sources")


if __name__ == "__main__":
    main()
